name: SuckChat
main: me.cosban.suckchat.SuckChat
author: Cosban
website: http://phantomcraft.net/
description: Because chat plugins need to suck a little bit less.
version: 0.3.0
softdepend: [PhantomClans, PermissionsEx]