name: SuckChat
main: me.cosban.suckchat.SuckChat
author: Cosban
website: http://phantomcraft.net/wiki/SuckChat
description: Because chat plugins need to suck a little bit less.
version: 0.3.0
softdepend: [PhantomClans, PermissionsEx, bPermissions]
commands:
  pm:
    description: Private message players.
    aliases: [tell,whisper,msg]
  r:
    description: Reply to a pm
    aliases: [reply]
  ch:
    description: Base channels command.
  irc:
    description: Send a message to IRC only.
  suckchat:
    description: General Commands
  muteip:
    description: Mutes an entire IP
  mute:
    description: Mutes a specific player
  unmute:
    description: Unmutes a specific player
  me:
    description: Emote something
permissions:
  chat.*:
    description: All chat permissions.
    children:
      chat.variables.*: true
      chat.mute: true
      chat.pm.*: true
      chat.emote: true
      chat.channels.*: true
      chat.irc.*: true
  chat.variables.*:
    description: All variable based chat
    children:
      chat.variables.colors: true
      chat.variables.names: true
  chat.pm.*:
    description: All private message perms
    children:
      chat.pm.send: true
      chat.pm.eavesdrop: true
  chat.channels.*:
    description: All channel perms
    children:
      chat.channels.join: true
      chat.channels.send: true
      chat.channels.listen: true
      chat.channels.leave: true
  chat.irc.*:
    description: All irc perms
  chat.variables.colors:
    description: Allows usage of colored chat
  chat.variables.names:
    description: Allows usage of variable names in chat
  chat.pm.send:
    description: Allows players to send private messages
  chat.pm.eavesdrop:
    description: Allows players to view private messages not sent to them
  chat.channels.join:
    description: Allows players to join chat channels
  chat.channels.send:
    description: Allows players to send messages to specific channels
  chat.channels.listen:
    description: Allows players to listen in on a channel
  chat.channels.leave:
    description: Allows players to leave chat channels
  chat.emote:
    description: Allows players to emote
  chat.mute:
    description: Allows players to mute other players.
  chat.noshow:
    description: Given to groups so that their name isn't shown in chat